apiVersion: v1
kind: Service
metadata:
    name: "koamano-website"
    labels:
        app: "koamano-website"
spec:
    ports:
    - port: 3000
      targetPort: 3000
    selector:
        app: "koamano-website"
    type: LoadBalancer